# Generated by Django 4.2.1 on 2023-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdelegation',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetdelegation',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetDelegation',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
